export default {
  GET_POSTS: "GET_POSTS",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",

  GET_POST_DETAILS: "GET_POST_DETAILS",
  GET_POST_DETAILS_SUCCESS: "GET_POST_DETAILS_SUCCESS",
  GET_POST_DETAILS_FAIL: "GET_POST_DETAILS_FAIL",

  GET_POST_COMMENTS: "GET_POST_COMMENTS",
  GET_POST_COMMENTS_SUCCESS: "GET_POST_COMMENTS_SUCCESS",
  GET_POST_COMMENTS_FAIL: "GET_POST_COMMENTS_FAIL",

  HANDLE_TABLE_PAGE: "HANDLE_TABLE_PAGE",
};
